export const PortugalCOVIDCases = new Map([
	['Abrantes', 4],
	['Águeda', 32],
	['Albergaria-a-Velha', 52],
	['Albufeira', 55],
	['Alcácer do Sal', 5],
	['Alcanena', 3],
	['Alcobaça', 7],
	['Alcochete', 9],
	['Alenquer', 15],
	['Almada', 148],
	['Almeida', 6],
	['Almeirim', 10],
	['Alpiarça', 6],
	['Alvaiázere', 23],
	['Amadora', 159],
	['Amarante', 39],
	['Amares', 28],
	['Anadia', 15],
	['Ansião', 4],
	['Arcos de Valdevez', 42],
	['Arganil', 4],
	['Arouca', 26],
	['Aveiro', 165],
	['Baião', 6],
	['Barcelos', 141],
	['Barreiro', 75],
	['Batalha', 4],
	['Beja', 6],
	['Benavente', 27],
	['Bombarral', 3],
	['Braga', 647],
	['Bragança', 85],
	['Cabeceiras de Basto', 8],
	['Cadaval', 3],
	['Caldas da Rainha', 7],
	['Calheta (Açores)', 5],
	['Câmara de Lobos', 7],
	['Caminha', 9],
	['Cantanhede', 27],
	['Carraz. de Ansiães', 5],
	['Carregal do Sal', 7],
	['Cartaxo', 18],
	['Cascais', 264],
	['Castelo de Paiva', 7],
	['Castro Daire', 91],
	['Celorico da Beira', 7],
	['Celorico de Basto', 9],
	['Chaves', 19],
	['Cinfães', 7],
	['Coimbra', 275],
	['Condeixa-a-Nova', 41],
	['Coruche', 16],
	['Covilhã', 5],
	['Elvas', 4],
	['Espinho', 45],
	['Esposende', 28],
	['Estarreja', 46],
	['Évora', 21],
	['Fafe', 30],
	['Faro', 52],
	['Felgueiras', 163],
	['Figueira da Foz', 13],
	['Figueira de Castelo Rodrigo', 3],
	['Figueiró dos Vinhos', 4],
	['Funchal', 26],
	['Góis', 6],
	['Gondomar', 701],
	['Gouveia', 13],
	['Grândola', 6],
	['Guarda', 16],
	['Guimarães', 214],
	['Horta', 6],
	['Ílhavo', 88],
	['Lagoa (Faro)', 3],
	['Lagos', 3],
	['Lamego', 15],
	['Leiria', 38],
	['Lisboa', 905],
	['Loulé', 42],
	['Loures', 201],
	['Lourinhã', 4],
	['Lousã', 8],
	['Lousada', 124],
	['Macedo de Cavaleiros', 18],
	['Madalena', 5],
	['Mafra', 55],
	['Maia', 600],
	['Mangualde', 50],
	['Marco de Canaveses', 45],
	['Marinha Grande', 12],
	['Matosinhos', 715],
	['Mealhada', 13],
	['Melgaço', 14],
	['Miranda do Corvo', 8],
	['Miranda do Douro', 4],
	['Mirandela', 17],
	['Moimenta da Beira', 8],
	['Moita', 52],
	['Monção', 20],
	['Montemor-o-Velho', 14],
	['Montijo', 40],
	['Moura', 22],
	['Murtosa', 6],
	['Nelas', 13],
	['Óbidos', 3],
	['Odivelas', 141],
	['Oeiras', 168],
	['Olhão', 12],
	['Oliveira de Azeméis', 118],
	['Oliveira de Frades', 8],
	['Oliveira do Bairro', 15],
	['Oliveira do Hospital', 6],
	['Ourém', 26],
	['Ovar', 416],
	['Paços de Ferreira', 163],
	['Palmela', 15],
	['Paredes', 165],
	['Paredes de Coura', 6],
	['Penacova', 9],
	['Penafiel', 98],
	['Peniche', 7],
	['Peso da Régua', 15],
	['Pinhel', 9],
	['Pombal', 32],
	['Ponta do Sol', 5],
	['Ponte da Barca', 4],
	['Ponte de Lima', 19],
	['Portimão', 30],
	['Porto', 921],
	['Porto de Mós', 4],
	['Porto Santo', 5],
	['Póvoa de Lanhoso', 29],
	['Póvoa de Varzim', 62],
	['Reg. de Monsaraz', 8],
	['Resende', 53],
	['Rio Maior', 9],
	['Sabrosa', 4],
	['Salvaterra de Magos', 5],
	['Santa Comba Dão', 4],
	['Santa Cruz', 6],
	['Santa Maria da Feira', 279],
	['Santarém', 47],
	['Santiago do Cacém', 11],
	['Santo Tirso', 149],
	['São João da Madeira', 45],
	['São Pedro do Sul', 8],
	['São Roque do Pico', 3],
	['Sátão', 5],
	['Seia', 5],
	['Seixal', 129],
	['Serpa', 17],
	['Sesimbra', 17],
	['Setúbal', 55],
	['Sever do Vouga', 7],
	['Silves', 19],
	['Sines', 4],
	['Sintra', 397],
	['Soure', 12],
	['Tábua', 15],
	['Tavira', 29],
	['Terras de Bouro', 7],
	['Tomar', 9],
	['Tondela', 8],
	['Torre de Moncorvo', 22],
	['Torres Novas', 9],
	['Torres Vedras', 26],
	['Trancoso', 12],
	['Trofa', 84],
	['Vagos', 13],
	['Vale de Cambra', 60],
	['Valença', 6],
	['Valongo', 491],
	['Valpaços', 5],
	['Velas', 6],
	['Viana do Castelo', 104],
	['Vieira do Minho', 15],
	['Vila Praia da Vitória', 8],
	['Vila do Conde', 130],
	['Vila Flor', 5],
	['Vila Franca de Xira', 62],
	['Vila Nova da Barquinha', 3],
	['Vila Nova de Cerveira', 4],
	['Vila Nova de Famalicão', 225],
	['Vila Nova de Foz Côa', 68],
	['Vila Nova de Gaia', 842],
	['Vila Nova de Poiares', 3],
	['Vila Pouca de Aguiar', 3],
	['Vila Real', 138],
	['Vila Real Santo António', 14],
	['Vila Verde', 87],
	['Vimioso', 8],
	['Vinhais', 10],
	['Viseu', 69],
	['Vizela', 26],
]);
