FROM node

WORKDIR /backend
ENV PATH /backend/node_modules/.bin:$PATH

RUN curl https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz | tar -C /usr/local -xz && /usr/local/go/bin/go get github.com/google/codesearch/cmd/...

COPY backend/package.json backend/yarn.lock ./
RUN yarn

COPY backend .

WORKDIR /frontend
COPY frontend .
RUN yarn 
RUN yarn build

WORKDIR /backend
